// Presentation only: no database writes or changes to payment requests.
const BWSView=(()=>{
 const copy={
  party:{title:'Party Boat',intro:'A party at sea along Bávaro’s flat, palm-lined coastline. Enjoy music, dancing and ocean views, with snorkeling and a stop at the natural pool.',facts:'3.5 hours · Ages 18+ · Adults only',included:['Coastal cruise, music and party atmosphere','Snorkeling and a natural pool stop','Rum, beer and soft drinks','Transportation included'],notes:['Pickup location and coverage will be confirmed.','Bring swimwear, a towel, sunscreen and money for optional purchases.','The itinerary is subject to weather and sea conditions.']},
  para:{title:'Parasailing',intro:'See Bávaro’s turquoise waters and white-sand coast from above. Takeoff and landing take place on the boat using a crew-operated winch. Choose a solo flight or fly together as a pair or a group of three.',facts:'10–15 minutes in the air · Ages 10+ · English and Spanish',included:['Parasailing flight','Required safety equipment'],excluded:['Transportation to or from your accommodation','Photos and videos, tips and souvenirs','Food, drinks and additional services'],notes:['Minors must be accompanied and supervised by an adult.','Safety equipment is mandatory. Participation under the influence of alcohol or drugs is not allowed.','Not recommended during pregnancy or for people with reduced mobility. Not wheelchair accessible.','The captain confirms the flight arrangement based on wind and participants’ weight. Contact us before booking if you have questions.','Bring swimwear, comfortable clothing, water-friendly footwear, biodegradable sunscreen and a change of clothes.','Cameras and personal belongings remain in your care. Follow the crew’s instructions.']},
  charter:{title:'Fishing Charter',intro:'Enjoy a private fishing trip with your own group. Choose four hours in the morning, four hours in the afternoon or a full eight-hour day. The price is for the charter, not per passenger.',facts:'4 or 8 hours · Private trip · 6–7 fishing lines',included:['Captain, guide, fishing equipment and bait','Water, soft drinks and beer','4-hour trips: sandwiches and snacks','8-hour trips: lunch','Transportation included'],notes:['Pickup location and coverage will be confirmed.','Booking is available once passenger capacity and departures are confirmed.','Fishing lines are shared by the group; not everyone fishes simultaneously.']},
  fish:{title:'Shared Fishing',intro:'Book your own fishing place and join other anglers on a shared boat. You may meet travelers from different hotels and groups. This is a shared excursion, not a private charter.',facts:'4 hours · Price per angler',included:['Round-trip hotel transportation','Water, soft drinks and beer','Captain and guide with basic English','Fishing equipment and bait'],excluded:['Meals and snacks'],notes:['The boat accommodates up to 7 anglers and 3 observers.','This booking is for anglers only. Contact us about observer availability and pricing.']},
  cat:{title:'Catalina Island Excursion',intro:'Spend a full day exploring Catalina Island. An island excursion with lunch and an open bar, designed for a day away from the mainland.',facts:'Full day',included:['Lunch','Open bar'],notes:['Contact us for the detailed itinerary, pickup arrangements and included equipment before booking.']}
 };
 const pairs=[
 ['Party Boat','Party Boat'],['Shared Fishing','Pesca compartida'],['Fishing Charter','Charter de pesca'],['Catalina Island Excursion','Excursión a Isla Catalina'],['Saona Island','Isla Saona'],['Discover Scuba Diving','Buceo de iniciación'],['Snorkeling','Snorkeling'],
 ['A party at sea along Bávaro’s flat, palm-lined coastline. Enjoy music, dancing and ocean views, with snorkeling and a stop at the natural pool.','Una fiesta en el mar frente a la costa llana de Bávaro, entre playas y palmeras. Disfruta de música, baile y vistas al mar, con snorkeling y una parada en la piscina natural.'],
 ['3.5 hours · Ages 18+ · Adults only','3 horas y media · Desde 18 años · Solo adultos'],['Coastal cruise, music and party atmosphere','Recorrido por la costa, música y ambiente de fiesta'],['Snorkeling and a natural pool stop','Snorkeling y parada en la piscina natural'],['Rum, beer and soft drinks','Ron, cerveza y refrescos'],['Transportation included','Transporte incluido'],['Pickup location and coverage will be confirmed.','Confirmaremos el punto de recogida y la cobertura del transporte.'],['Bring swimwear, a towel, sunscreen and money for optional purchases.','Lleva traje de baño, toalla, protector solar y dinero para compras opcionales.'],['The itinerary is subject to weather and sea conditions.','El recorrido está sujeto al clima y al estado del mar.'],
 ['See Bávaro’s turquoise waters and white-sand coast from above. Takeoff and landing take place on the boat using a crew-operated winch. Choose a solo flight or fly together as a pair or a group of three.','Contempla desde el aire las aguas turquesas y la costa de arena blanca de Bávaro. El despegue y el aterrizaje se realizan desde la embarcación mediante un cable controlado por la tripulación. Vuela solo, en pareja o con dos acompañantes.'],['10–15 minutes in the air · Ages 10+ · English and Spanish','10–15 minutos de vuelo · Desde 10 años · Español e inglés'],['Parasailing flight','Vuelo en Parasailing'],['Required safety equipment','Equipo de seguridad necesario'],['Transportation to or from your accommodation','Transporte desde o hacia el alojamiento'],['Photos and videos, tips and souvenirs','Fotografías y vídeos, propinas y souvenirs'],['Food, drinks and additional services','Alimentos, bebidas y servicios adicionales'],['Minors must be accompanied and supervised by an adult.','Los menores deben estar acompañados y supervisados por un adulto.'],['Safety equipment is mandatory. Participation under the influence of alcohol or drugs is not allowed.','El equipo de seguridad es obligatorio. No se permite participar bajo los efectos del alcohol o las drogas.'],['Not recommended during pregnancy or for people with reduced mobility. Not wheelchair accessible.','No se recomienda durante el embarazo ni para personas con movilidad reducida. Sin acceso para sillas de ruedas.'],['The captain confirms the flight arrangement based on wind and participants’ weight. Contact us before booking if you have questions.','El capitán confirma la modalidad según el viento y el peso de los participantes. Escríbenos antes de reservar si tienes dudas.'],['Bring swimwear, comfortable clothing, water-friendly footwear, biodegradable sunscreen and a change of clothes.','Lleva traje de baño, ropa cómoda, calzado apto para el agua, protector solar biodegradable y un cambio de ropa.'],['Cameras and personal belongings remain in your care. Follow the crew’s instructions.','El cuidado de cámaras y objetos personales corresponde a cada participante. Sigue las indicaciones de la tripulación.'],
 ['Enjoy a private fishing trip with your own group. Choose four hours in the morning, four hours in the afternoon or a full eight-hour day. The price is for the charter, not per passenger.','Disfruta de una salida de pesca privada con tu grupo. Elige cuatro horas por la mañana, cuatro por la tarde o una jornada completa de ocho horas. El precio corresponde al charter completo, no a cada pasajero.'],['4 or 8 hours · Private trip · 6–7 fishing lines','4 u 8 horas · Excursión privada · 6–7 líneas de pesca'],['Captain, guide, fishing equipment and bait','Capitán, guía, equipo de pesca y cebos'],['Water, soft drinks and beer','Agua, refrescos y cerveza'],['4-hour trips: sandwiches and snacks','Salidas de 4 horas: sándwiches y aperitivos'],['8-hour trips: lunch','Salidas de 8 horas: almuerzo'],['Booking is available once passenger capacity and departures are confirmed.','La reserva estará disponible cuando se confirmen la capacidad de pasajeros y las salidas.'],['Fishing lines are shared by the group; not everyone fishes simultaneously.','El grupo comparte las líneas de pesca; no todos pescan al mismo tiempo.'],
 ['Book your own fishing place and join other anglers on a shared boat. You may meet travelers from different hotels and groups. This is a shared excursion, not a private charter.','Reserva tu plaza de pescador y comparte la embarcación con otros aficionados, que pueden venir de diferentes hoteles y grupos. Es una excursión compartida, no un charter privado.'],['4 hours · Price per angler','4 horas · Precio por pescador'],['Round-trip hotel transportation','Transporte de ida y vuelta al hotel'],['Captain and guide with basic English','Capitán y guía con inglés básico'],['Fishing equipment and bait','Equipo de pesca y cebos'],['Meals and snacks','Comida y aperitivos'],['The boat accommodates up to 7 anglers and 3 observers.','La embarcación admite hasta 7 pescadores y 3 observadores.'],['This booking is for anglers only. Contact us about observer availability and pricing.','Esta reserva es solo para pescadores. Consulta la disponibilidad y el precio para observadores.'],
 ['Spend a full day exploring Catalina Island. An island excursion with lunch and an open bar, designed for a day away from the mainland.','Disfruta de un día completo en Isla Catalina, con almuerzo y barra libre. Una excursión para descubrir la isla y desconectar frente al mar.'],['Full day','Día completo'],['Lunch','Almuerzo'],['Open bar','Barra libre'],['Contact us for the detailed itinerary, pickup arrangements and included equipment before booking.','Consulta el itinerario detallado, la recogida y el equipo incluido antes de reservar.'],
 ['Included','Incluye'],['Not included','No incluye'],['Before you go','Antes de ir'],['BOOK NOW','RESERVAR'],['COMING SOON','PRÓXIMAMENTE'],['CONTINUE TO PAYPAL','CONTINUAR A PAYPAL'],['DATE','FECHA'],['GUESTS','PASAJEROS'],['TIME / DEPARTURE','HORA / SALIDA'],['CHOOSE YOUR FLIGHT','ELIGE TU VUELO'],['CHOOSE YOUR CHARTER','ELIGE TU CHARTER'],['per person','por persona'],['per angler','por pescador'],['🚐 Pickup available','🚐 Consulta la recogida'],['Book your Punta Cana experience in seconds.','Tu próxima experiencia en Punta Cana empieza aquí.'],['No account · No app · PayPal Sandbox Beta','Sin cuenta · Sin app · PayPal Sandbox Beta'],['Questions? Chat with us on WhatsApp','¿Tienes preguntas? Escríbenos por WhatsApp'],['Activity images are illustrative.','Las imágenes de las actividades son ilustrativas.'],['BWS Beta · Prices and schedules may be adjusted during beta.','BWS Beta · Los precios y horarios pueden cambiar durante la beta.'],['Loading experiences…','Cargando experiencias…'],['Please select your guests.','Selecciona los pasajeros.'],['Experiences are temporarily unavailable. Please refresh to try again.','Las experiencias no están disponibles temporalmente. Recarga para intentarlo de nuevo.'],['This experience is currently unavailable for the selected guests. Please refresh.','Esta experiencia no está disponible para los pasajeros seleccionados. Recarga la página.'],['The price has changed. Please refresh to see the current total.','El precio ha cambiado. Recarga para ver el total actual.'],['Booking service unavailable. Please try again shortly.','El servicio de reservas no está disponible. Inténtalo de nuevo en unos momentos.'],
 ['BOOKING RECEIPT ✓','COMPROBANTE DE RESERVA ✓'],['MEETING & PICKUP','ENCUENTRO Y RECOGIDA'],['Pickup details will be confirmed by Bávaro Water Sports.','Bávaro Water Sports confirmará los detalles de recogida.'],['IMPORTANT — BE ON TIME','IMPORTANTE — LLEGA PUNTUAL'],['Please be at your pickup point 15 minutes before the scheduled time. Shared transportation cannot wait for late passengers.','Llega al punto de recogida 15 minutos antes de la hora indicada. El transporte compartido no puede esperar a pasajeros que lleguen tarde.'],['BEFORE YOU GO','ANTES DE IR'],['Activity-specific instructions will appear here when confirmed.','Las instrucciones de la actividad aparecerán aquí cuando estén confirmadas.'],['Scan to reopen this booking receipt.','Escanea para volver a abrir este comprobante.'],['Need help with your booking?','¿Necesitas ayuda con tu reserva?'],['Contact us on WhatsApp','Contáctanos por WhatsApp'],['Save as image','Guardar como imagen'],['Copy link','Copiar enlace'],['Send by WhatsApp','Compartir por WhatsApp'],['Print / Save PDF','Imprimir / Guardar PDF'],['Creating image…','Creando imagen…'],['PAID','PAGADO'],['Customer:','Cliente:'],['Property:','Alojamiento:'],
 ['Beach · Boat · Natural pool · Caribbean escape','Playa · Barco · Piscina natural · Escapada al Caribe'],['Your first scuba experience','Tu primera experiencia de buceo'],['Beginner experience','Experiencia de iniciación'],['Explore the Caribbean below the surface','Descubre el Caribe bajo el agua'],['Local experience','Experiencia local']
 ];
 const dictionary=new Map(pairs),seen=new WeakMap();let lang='en';
 try{lang=localStorage.getItem('bws_lang')||((navigator.language||'').startsWith('es')?'es':'en')}catch{}
 function translate(text){
  const clean=text.trim();if(dictionary.has(clean))return text.replace(clean,dictionary.get(clean));
  return text.replace('Total:','Total:').replace(/CHOOSE YOUR/g,'ELIGE TU').replace(/ person flies/g,' persona vuela').replace(/ people fly together/g,' personas vuelan juntas').replace(/4 hours · Morning/g,'4 horas · Mañana').replace(/4 hours · Afternoon/g,'4 horas · Tarde').replace(/8 hours/g,'8 horas').replace(/Private Charter/g,'Charter privado').replace(/Up to (\d+) guests/g,'Hasta $1 pasajeros').replace(/(\d+) people/g,'$1 personas').replace(/(\d+) person\b/g,'$1 persona').replace(/(\d+) Guest\(s\)/g,'$1 pasajero(s)').replace(/Receipt /g,'Reserva ').replace(/🕒 Full day/g,'🕒 Día completo').replace(/🕒 Beginner experience/g,'🕒 Experiencia de iniciación').replace(/🕒 Local experience/g,'🕒 Experiencia local');
 }
 function localize(){
  if(typeof document==='undefined'||!document.documentElement)return;
  document.documentElement.lang=lang;
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
  while(node=walker.nextNode()){
   if(['SCRIPT','STYLE'].includes(node.parentElement?.tagName))continue;
   const previous=seen.get(node),source=previous&&node.nodeValue===previous.output?previous.source:node.nodeValue;
   const output=lang==='es'?translate(source):source;seen.set(node,{source,output});if(node.nodeValue!==output)node.nodeValue=output;
  }
  document.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===lang)));
 }
 function enhance(c,a,key){
  if(a.pricing_type==='private_charter')key='charter';const info=copy[key];c.id=key;c.dataset.activity=a.id;
  if(!info)return;
  c.querySelector('h2').textContent=info.title;c.querySelector('.desc').textContent=info.intro;
  c.querySelectorAll('.meta').forEach(el=>{if(el.textContent.includes('Pickup')||el.textContent.includes('🕒'))el.remove()});
  if(key==='fish')c.querySelector('.meta').textContent='per angler';
  const content=document.createElement('div');content.className='experience-copy';
  const facts=document.createElement('p');facts.className='facts';facts.textContent=info.facts;content.appendChild(facts);
  for(const [field,title] of [['included','Included'],['excluded','Not included'],['notes','Before you go']]){
   if(!info[field])continue;const details=document.createElement('details');details.open=field==='included';const summary=document.createElement('summary');summary.textContent=title;details.appendChild(summary);const list=document.createElement('ul');info[field].forEach(text=>{const li=document.createElement('li');li.textContent=text;list.appendChild(li)});details.appendChild(list);content.appendChild(details);
  }
  c.querySelector('.desc').after(content);
  if(key==='para'){
   const gallery=document.createElement('div');gallery.className='activity-gallery';
   for(let n=1;n<=5;n++){const img=document.createElement('img');img.src='assets/activities/parasailing-photo-'+n+'.webp';img.alt='Parasailing';img.loading='lazy';img.width=360;img.height=240;gallery.appendChild(img)}content.appendChild(gallery);
  }
 }
 function init(){
  const bar=document.createElement('div');bar.className='language-switch';bar.setAttribute('aria-label','Language / Idioma');
  for(const value of ['es','en']){const button=document.createElement('button');button.dataset.language=value;button.textContent=value.toUpperCase();button.onclick=()=>{lang=value;try{localStorage.setItem('bws_lang',lang)}catch{}localize()};bar.appendChild(button)}document.querySelector('header').prepend(bar);
  const nav=document.createElement('nav');nav.className='activity-nav';nav.setAttribute('aria-label','Activities / Actividades');
  for(const [key,title] of [['party','Party Boat'],['para','Parasailing'],['charter','Fishing Charter'],['fish','Shared Fishing'],['cat','Catalina Island Excursion'],['saona','Saona Island'],['scuba','Discover Scuba Diving'],['snorkel','Snorkeling']]){const link=document.createElement('a');link.href='#'+key;link.textContent=title;nav.appendChild(link)}document.querySelector('header').appendChild(nav);
  new MutationObserver(localize).observe(document.body,{childList:true,subtree:true,characterData:true});localize();
 }
 document.addEventListener('DOMContentLoaded',init);
 return {enhance,localize};
})();
